workersPerRun: 1
runtimePerRun: 1h
runs: 10
targets:
  - dir: targets/dns
    name: FuzzLookupHostEmptySeed
  - dir: targets/gzip
    name: FuzzGZIPReaderEmptySeed
  - dir: targets/html
    name: FuzzParseEmptySeed
  - dir: targets/html
    name: FuzzParseWithOptionsEmptySeed
  - dir: targets/html
    name: FuzzParseFragmentEmptySeed
  - dir: targets/html
    name: FuzzParseFragmentWithOptionsEmptySeed
  - dir: targets/html
    name: FuzzTokenizerEmptySeed
  - dir: targets/http
    name: FuzzClientResponseEmptySeed
  - dir: targets/image
    name: FuzzImageDecodeEmptySeed
  - dir: targets/json
    name: FuzzUnmarshalJSONEmptySeed
  - dir: targets/json
    name: FuzzUnmarshalJSONBasicSeed
  - dir: targets/json
    name: FuzzDecoderTokenEmptySeed
  - dir: targets/json
    name: FuzzDecoderTokenBasicSeed
  - dir: targets/tar
    name: FuzzTarReaderEmptySeed
  - dir: targets/tls
    name: FuzzTLSClientHandshakeEmptySeed
  - dir: targets/tls
    name: FuzzTLSServerHandshakeEmptySeed
  - dir: targets/url
    name: FuzzParseQueryEmptySeed
  - dir: targets/url
    name: FuzzParseQueryBasicSeed
  - dir: targets/zip
    name: FuzzZIPReaderEmptySeed
